# Generated by Django 4.1 on 2022-08-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ano', models.DecimalField(decimal_places=0, max_digits=4)),
                ('sinopse', models.TextField(max_length=1000)),
                ('genero', models.CharField(choices=[('R', 'Romance'), ('FC', 'Ficção científica'), ('D', 'Distopia'), ('AA', 'Ação e aventura'), ('H', 'Horror'), ('FP', 'Ficção Policial'), ('B', 'Biografia'), ('FH', 'Ficção histórica'), ('DC', 'Documentário')], default='AA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('filme', models.ManyToManyField(to='filmes.filme')),
            ],
        ),
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('filme', models.ManyToManyField(to='filmes.filme')),
            ],
        ),
    ]
