# Generated by Django 4.1 on 2022-08-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='imagem',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
